version: '2'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        ports:
            - "4567:4567"  
            
    dbmongo:
        image: mongo:3.6.1
        container_name: dbmongo
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config:
    
networks:
  default:
    external:
      name: backend