version: '2'

services:
    lbnginx:
        build:
            context: .
            dockerfile: Dockerfile
        image: nginx:alpine
        container_name: lbnginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:8080"
            - "443:443"

networks:
  default:
    external:
      name: backend
          
